spring:
  application:
    name: FluxDigitalStore
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fluxdb
    username: postgres
    password: tfExHHwJvql4Q51o
  jpa:
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: localhost
    port: 8025

---

server:
  port: 8080
  error:
    include-stacktrace: never

---

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

---

jwt:
  secret: dfb2f5463449b24862a52ae5547c3cc5
  company_name: Artem_Hontar
  expiry_in_sec: 604800

rpt:
  expiry_in_msec: 600000

encryption:
  salt:
    rounds: 10

email:
  from: store@fluxdigital.com